# Generated by Django 2.0.3 on 2018-04-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badpress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='URL_logo',
        ),
        migrations.RemoveField(
            model_name='state',
            name='info',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
