# Generated by Django 2.0.3 on 2018-04-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badpress', '0012_auto_20180417_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badpress.State'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badpress.State'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
