# Generated by Django 2.0.3 on 2018-04-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badpress', '0010_auto_20180417_1445'),
        ('badpress', '0019_auto_20180419_1518'),
    ]

    operations = [
    ]
