# Generated by Django 2.0.3 on 2018-05-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badpress', '0020_merge_20180428_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word_1', models.CharField(max_length=250)),
                ('word_2', models.CharField(max_length=250)),
                ('word_3', models.CharField(max_length=250)),
                ('word_4', models.CharField(max_length=250)),
                ('word_5', models.CharField(max_length=250)),
                ('word_6', models.CharField(max_length=250)),
                ('word_7', models.CharField(max_length=250)),
                ('word_8', models.CharField(max_length=250)),
                ('word_9', models.CharField(max_length=250)),
                ('word_10', models.CharField(max_length=250)),
                ('word_11', models.CharField(max_length=250)),
                ('word_12', models.CharField(max_length=250)),
                ('word_13', models.CharField(max_length=250)),
                ('word_14', models.CharField(max_length=250)),
                ('word_15', models.CharField(max_length=250)),
                ('word_16', models.CharField(max_length=250)),
                ('word_17', models.CharField(max_length=250)),
                ('word_18', models.CharField(max_length=250)),
                ('word_19', models.CharField(max_length=250)),
                ('word_20', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('april', models.IntegerField()),
                ('may', models.IntegerField()),
                ('june', models.IntegerField()),
                ('july', models.IntegerField()),
                ('august', models.IntegerField()),
                ('september', models.IntegerField()),
                ('october', models.IntegerField()),
                ('november', models.IntegerField()),
                ('december', models.IntegerField()),
                ('january', models.IntegerField()),
                ('february', models.IntegerField()),
                ('march', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badpress.State'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, choices=[('r', 'Republican'), ('d', 'Democrat'), ('i', 'Independent'), ('o', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badpress.State'),
        ),
    ]
