# Generated by Django 2.0.3 on 2018-05-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badpress', '0026_auto_20180503_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='last_name',
            field=models.CharField(default='LASt', max_length=250),
        ),
        migrations.AddField(
            model_name='popularity',
            name='last_name',
            field=models.CharField(default='LAST', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badpress.State'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badpress.State'),
        ),
    ]
