# Generated by Django 2.0.3 on 2018-05-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badpress', '0028_auto_20180503_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badpress.State'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badpress.State'),
        ),
    ]
